spring:
  datasource:
    url: jdbc:mysql://172.18.0.2:3306/test_db?autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  thymeleaf:
    cache: false
    encoding: UTF-8
    suffix: .html

server:
  port: 8089
  servlet:
    context-path: /testsystem

